frr defaults datacenter
hostname rr
password frr
service integrated-vtysh-config
# --8<-- [start:eth1-interface]
interface eth1
 ip address 192.168.99.2/30
interface lo
 ip address 10.0.0.99/32
# --8<-- [end:eth1-interface]
# --8<-- [start:def-route]
router bgp 100
 neighbor ibgp-overlay peer-group
 neighbor ibgp-overlay remote-as 100
 neighbor ibgp-overlay update-source lo
 neighbor ibgp-overlay advertisement-interval 1
 neighbor ibgp-overlay timers 3 9
 neighbor ibgp-overlay timers connect 1
 neighbor 10.0.0.1 peer-group ibgp-overlay
 neighbor 10.0.0.2 peer-group ibgp-overlay
 neighbor 10.0.0.3 peer-group ibgp-overlay
 neighbor 10.0.0.4 peer-group ibgp-overlay
 neighbor 192.168.99.1 remote-as 201
 neighbor 192.168.99.1 local-as 199
 !
address-family ipv4 unicast
  redistribute connected
 exit-address-family
!
 address-family l2vpn evpn
  neighbor ibgp-overlay activate
  neighbor ibgp-overlay route-reflector-client
 exit-address-family
exit
# --8<-- [end:def-route]
# --8<-- [start:lo-interface]
# --8<-- [end:lo-interface]
# --8<-- [start:bgp]
# --8<-- [end:bgp]
